print("Custom header: header1\r\n")
print("Content-length: 3000\r\n")
print("Content-Type: text/html\r")
print("\r")

print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("<head>")
print("    <meta charset=\"UTF-8\">")
print("    <link rel=\"stylesheet\" href=\"/Desktop/WebServ/pages/response_pages/style.css\">")
print("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
print("    <title>Example</title>")
print("</head>")
print("<body>")
print("    <h1>Example</h1>")
print("</body>")
print("</html>")